auth-service:
    tty: true
    command:
    - "-l"
    - "debug"
    - "-t"
    - "console"
    - "run"
    - "--db-host"
    - "mysql-master"
    - "-p"
    - "9000"
    image: rancherapps.com:5000/go-auth:deploy
    stdin_open: true
    links:
    - mysql-master:mysql-master

auth-lb:
  ports:
  - 9000:9000
  tty: true
  image: rancher/load-balancer-service
  links:
  - auth-service:auth-service
  stdin_open: true

mysql-master:
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: messenger
    MYSQL_USER: messenger
    MYSQL_PASSWORD: messenger
  tty: true
  image: mysql:5.6
  stdin_open: true
